# Generated by Django 4.1.5 on 2023-02-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
